
-- -----------------------------------------------------------------------------
--       TABLE : ETAPE
-- -----------------------------------------------------------------------------

CREATE TABLE ETAPE
   (
    NUM_COURSE NUMBER(4)  NOT NULL,
    NUM_ETAPE NUMBER(2)  NOT NULL,
    NUM_TYPE_ETAPE NUMBER(2)  NULL,
    NB_KM_ETAPE NUMBER(4,1)  NULL,
    DATE_ETAPE TIMESTAMP(3)  NULL
,   CONSTRAINT PK_ETAPE PRIMARY KEY (NUM_COURSE, NUM_ETAPE)  USING INDEX TABLESPACE BD50_IND 
   )
PARTITION BY LIST (NUMCOURSE) (
PARTITION etape_08 VALUES (2008) TABLESPACE BD50_DATA,
PARTITION etape_09 VALUES (2009) TABLESPACE BD50_DATA,
PARTITION etape_10 VALUES (2010) TABLESPACE BD50_DATA,
PARTITION etape_11 VALUES (2011) TABLESPACE BD50_DATA,
PARTITION etape_12 VALUES (2012) TABLESPACE BD50_DATA,
PARTITION etape_13 VALUES (2013) TABLESPACE BD50_DATA);

-- -----------------------------------------------------------------------------
--       TABLE : COURIR
-- -----------------------------------------------------------------------------

CREATE TABLE COURIR
   (
    NUM_DOSSARD NUMBER(3)  NOT NULL,
    NUM_COURSE NUMBER(4)  NOT NULL,
    NUM_ETAPE NUMBER(2)  NOT NULL,
    TEMPS_GENERAL INTERVAL DAY(2) TO SECOND(3)  NULL,
    POINTS_SPRINT_GENERAL NUMBER(3)  NULL,
    POINTS_MONTAGNE_GENERAL NUMBER(3)  NULL
,   CONSTRAINT PK_COURIR PRIMARY KEY (NUM_DOSSARD, NUM_COURSE, NUM_ETAPE)  USING INDEX TABLESPACE BD50_IND 
   )
PARTITION BY LIST (NUMCOURSE) (
PARTITION courir_08 VALUES (2008) TABLESPACE BD50_DATA,
PARTITION courir_09 VALUES (2009) TABLESPACE BD50_DATA,
PARTITION courir_10 VALUES (2010) TABLESPACE BD50_DATA,
PARTITION courir_11 VALUES (2011) TABLESPACE BD50_DATA,
PARTITION courir_12 VALUES (2012) TABLESPACE BD50_DATA,
PARTITION courir_13 VALUES (2013) TABLESPACE BD50_DATA);
