-- -----------------------------------------------------------------------------
--       TABLE : PARTICIPANT
-- -----------------------------------------------------------------------------

CREATE TABLE PARTICIPANT
   (
    NUM_COURSE NUMBER(4)  NOT NULL,
    NUM_DOSSARD NUMBER(3)  NOT NULL,
    NUM_COUREUR NUMBER(2)  NOT NULL,
    CODE_EQUIPE CHAR(3)  NOT NULL,
    NUM_ETAPE NUMBER(2)  NULL,
    KM NUMBER(4,1)  NULL,
    DESC_ABANDON VARCHAR2(255)  NULL,
    NOM_EQUIPE VARCHAR2(128)  NOT NULL
,   CONSTRAINT PK_PARTICIPANT PRIMARY KEY (NUM_COURSE, NUM_DOSSARD)  USING INDEX TABLESPACE BD50_IND 
   )
   ORGANIZATION INDEX
PARTITION BY LIST (NUMCOURSE) (
PARTITION participant_08 VALUES (2008) TABLESPACE BD50_DATA,
PARTITION participant_09 VALUES (2009) TABLESPACE BD50_DATA,
PARTITION participant_10 VALUES (2010) TABLESPACE BD50_DATA,
PARTITION participant_11 VALUES (2011) TABLESPACE BD50_DATA,
PARTITION participant_12 VALUES (2012) TABLESPACE BD50_DATA,
PARTITION participant_13 VALUES (2013) TABLESPACE BD50_DATA);

-- -----------------------------------------------------------------------------
--       TABLE : POINT_KM
-- -----------------------------------------------------------------------------

CREATE TABLE POINT_KM
   (
    NUM_COURSE NUMBER(4)  NOT NULL,
    NUM_ETAPE NUMBER(2)  NOT NULL,
    KM NUMBER(4,1)  NOT NULL,
    CODE_COMMUNE NUMBER(5)  NULL,
    CODE_CATEGORIE CHAR(5)  NULL,
    CODE_PAYS CHAR(2)  NULL,
    CODE_TYPE CHAR(5)  NULL,
    HEURE_PASSAGE_POINT_KM TIMESTAMP(3)  NULL,
    LIBELLE_TYPE VARCHAR2(128)  NULL,
    LIBELLE_CATEGORIE CHAR(32)  NULL
,   CONSTRAINT PK_POINT_KM PRIMARY KEY (NUM_COURSE, NUM_ETAPE, KM)  USING INDEX TABLESPACE BD50_IND 
   )
   ORGANIZATION INDEX
PARTITION BY LIST (NUMCOURSE) (
PARTITION point_km_08 VALUES (2008) TABLESPACE BD50_DATA,
PARTITION point_km_09 VALUES (2009) TABLESPACE BD50_DATA,
PARTITION point_km_10 VALUES (2010) TABLESPACE BD50_DATA,
PARTITION point_km_11 VALUES (2011) TABLESPACE BD50_DATA,
PARTITION point_km_12 VALUES (2012) TABLESPACE BD50_DATA,
PARTITION point_km_13 VALUES (2013) TABLESPACE BD50_DATA);

-- -----------------------------------------------------------------------------
--       TABLE : ATTEINDRE
-- -----------------------------------------------------------------------------

CREATE TABLE ATTEINDRE
   (
    NUM_DOSSARD NUMBER(3)  NOT NULL,
    NUM_COURSE NUMBER(4)  NOT NULL,
    NUM_ETAPE NUMBER(2)  NOT NULL,
    KM NUMBER(4,1)  NOT NULL,
    CLASSEMENT NUMBER(3)  NULL,
    HEURE_PASSAGE TIMESTAMP(3)  NULL
,   CONSTRAINT PK_ATTEINDRE PRIMARY KEY (NUM_DOSSARD, NUM_COURSE, NUM_ETAPE, KM)  USING INDEX TABLESPACE BD50_IND 
   )
   ORGANIZATION INDEX
   
PARTITION BY LIST (NUMCOURSE) (
PARTITION atteindre_08 VALUES (2008) TABLESPACE BD50_DATA,
PARTITION atteindre_09 VALUES (2009) TABLESPACE BD50_DATA,
PARTITION atteindre_10 VALUES (2010) TABLESPACE BD50_DATA,
PARTITION atteindre_11 VALUES (2011) TABLESPACE BD50_DATA,
PARTITION atteindre_12 VALUES (2012) TABLESPACE BD50_DATA,
PARTITION atteindre_13 VALUES (2013) TABLESPACE BD50_DATA);

