ANALYZE TABLE COUREUR VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE CATEGORIE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE TYPE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE PARTICIPANT VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE PAYS VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE BAREME VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE POINT_KM VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE EQUIPE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE MEMBRE_JURY VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE VILLE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE COURSE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE TYPE_ETAPE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE PARTENAIRE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE ETAPE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE COURIR VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE ATTEINDRE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE FAIRE_PARTIE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE VOTE_COMBATIF_ETAPE VALIDATE STRUCTURE CASCADE ;

ANALYZE TABLE CARAVANE VALIDATE STRUCTURE CASCADE ;