DROP TABLE COUREUR CASCADE CONSTRAINTS ;

DROP TABLE CATEGORIE CASCADE CONSTRAINTS ;

DROP TABLE TYPE CASCADE CONSTRAINTS ;

DROP TABLE PARTICIPANT CASCADE CONSTRAINTS ;

DROP TABLE PAYS CASCADE CONSTRAINTS ;

DROP TABLE BAREME CASCADE CONSTRAINTS ;

DROP TABLE POINT_KM CASCADE CONSTRAINTS ;

DROP TABLE EQUIPE CASCADE CONSTRAINTS ;

DROP TABLE MEMBRE_JURY CASCADE CONSTRAINTS ;

DROP TABLE VILLE CASCADE CONSTRAINTS ;

DROP TABLE COURSE CASCADE CONSTRAINTS ;

DROP TABLE TYPE_ETAPE CASCADE CONSTRAINTS ;

DROP TABLE PARTENAIRE CASCADE CONSTRAINTS ;

DROP TABLE ETAPE CASCADE CONSTRAINTS ;

DROP TABLE COURIR CASCADE CONSTRAINTS ;

DROP TABLE ATTEINDRE CASCADE CONSTRAINTS ;

DROP TABLE FAIRE_PARTIE CASCADE CONSTRAINTS ;

DROP TABLE VOTE_COMBATIF_ETAPE CASCADE CONSTRAINTS ;

DROP TABLE CARAVANE CASCADE CONSTRAINTS ;