-- Attention à l'ordre
DELETE FROM ATTEINDRE;
DELETE FROM VOTE_COMBATIF_ETAPE;
DELETE FROM MEMBRE_JURY;
DELETE FROM BAREME;
DELETE FROM COURIR;
DELETE FROM PARTICIPANT;
DELETE FROM POINT_KM;
DELETE FROM ETAPE;
DELETE FROM CATEGORIE;
DELETE FROM TYPE;
DELETE FROM TYPE_ETAPE;
DELETE FROM FAIRE_PARTIE;
DELETE FROM EQUIPE;
DELETE FROM CARAVANE.
DELETE FROM COURSE;
DELETE FROM COUREUR;
DELETE FROM PARTENAIRE;
DELETE FROM VILLE;
DELETE FROM PAYS;

